### PR TITLE
Added desktop notification feature. #17 closed

### PR DESCRIPTION
**Pull request by dkhurshudian**

### CODE REVIEW

**Comment by joeyespo** [comment]
Thanks for taking this on, @davo11122!

You did the hard part. Would you be up for adding this option to `options.html` too? If not, I'll pull this in and do that soon.

**Comment by dkhurshudian** [comment]
I'll do, but i need to know what should `options.html` contain.

**Comment by joeyespo** [comment]
Ok, awesome.

A checkbox under [this one](https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/options.html#L39-L46) with label "Show Desktop Notifications" and help text "When checked, notifications will pop up when new email arrives."

Then you'll have to add code to persist the option in `options.js` (see [useSnoozeColor](https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/options.js#L6) for a working example), and make your new code conditional using the new option (example [initialization](https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/background.js#L23), [loading](https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/background.js#L412), and [usage](https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/background.js#L135-L136)).

**Comment by dkhurshudian** [comment]
Done. we can include more details in notifiction popup(subjects, authors, etc..). what you think about it?

**Comment by joeyespo** [comment]
Thanks!

This looks good 👍 

Thanks for address this, @davo11122 😃

**Comment by joeyespo** [comment]
Just released v4.0.0 which includes this feature.

Thanks again!

**Comment by DaRkViVi** [comment]
Would it be possible to have some more infos in the notification popup? Like sender, subject, a preview of the email text?
Thanks!

**Pull request merged**
