### PR TITLE
Images optimized lossless

### PR DESCRIPTION
**Pull request by carloshbcabral**

### CODE REVIEW

**Comment by joeyespo** [comment]
Hey @CarlosHBC, thanks for the PR!

Could you give me a little more context to what you did here? I only dabble in design, so I may not know what to look for. Does this help with retina displays? Accessibility? Are the small images scaled down using better algorithms?

The only thing I could see with the naked eye is that the Available in the Chrome Store image is slightly more colorful. I thought I took that image directly from a Chrome Store samples page, but it's been a while, so I could be mis-remembering. Where'd you get the nicer image from?

Thanks!

**Comment by carloshbcabral** [comment]
All images were optimized without loss using [FileOptimizer](http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer), which is nothing more than a GUI to run several scripts with different algorithms.

Actually something went wrong with the Available in the Chrome Store image, but using Perforce P4Merge, is the only one that gave a problem.

The only advantage is having the files with a smaller size. :)

**Comment by joeyespo** [comment]
Ohhh, gotcha. Haha, so it ended up being a technical thing I'm actually familiar with, but didn't take the time to check the file sizes.

Thanks for doing this 😄 

Did you want to push a change with an updated Available in the Chrome Store image, since you bring that up, or is this good to go?

**Comment by joeyespo** [comment]
Releasing soon, so will pull now to get it in. Feel free to open a new PR if you wanted to update the Chrome Store image with something else.

Thanks for the optimizations, @CarlosHBC!

**Pull request merged**
