### PR TITLE
Use seconds instead of minutes

### PR DESCRIPTION
**Pull request by joeyespo**
Building off of #5 with a change to `setTimeout` and `periodInMinutes` to make it work.

### CODE REVIEW

**Comment by joeyespo** [comment]
@michliga Thoughts on switching to seconds?

**Comment by ghost** [comment]
@joeyespo Seconds would be great! We should switch the input in options.html to a number input because right now I think it's possible to enter any string (letters etc.). Or maybe a dropdown?

**Comment by joeyespo** [comment]
Ah, good point! The 'default user' input does this already. Agreed, this should work the same way.

Fixed in [bc87d7427030625f22432d9a6664ef8ac9338c63](https://github.com/joeyespo/inbox-by-gmail-checker/commit/bc87d7427030625f22432d9a6664ef8ac9338c63).

**Comment by ghost** [comment]
Awesome :+1:

**Comment by joeyespo** [comment]
Excellent! Thanks for your help, @michliga.

**Pull request merged**
