### PR TITLE
Polling setting

### PR DESCRIPTION
**Pull request by ghost**
#2

### CODE REVIEW

**Comment by joeyespo** [comment]
Thank you, @michliga! :smiley:

**Comment by ghost** [comment]
Thank you! @joeyespo

**Comment by joeyespo** [comment]
@michliga Made one tweak in 2bab1daeb61dfe27f026575d33759d00d8898514.

This allows the exponential backoff when the internet connection is lost, but has the side effect of one-check-per-hour be the maximum poll frequency now.

What do you think?

**Comment by ghost** [comment]
@joeyespo I can't imagine anyone would want the frequency to be more than an hour, so I think that's perfectly fine. I just wish there was a way to check more frequently than once per minute.

**Comment by joeyespo** [comment]
Excellent :+1: 

Yeah, it'd be nice if there was a general way to be more realtime, like push notifications for web projects or something.

In this case, what if we removed the [rounding step](https://github.com/joeyespo/inbox-by-gmail-checker/blob/2bab1daeb61dfe27f026575d33759d00d8898514/background.js#L140) and allow decimal values in the options. This would obviously make the browser extension more chatty, but at least you'd get closer to realtime when you need it.

**Comment by ghost** [comment]
I think that would be awesome, I mean if it's too chatty one can change the setting. My personal preference would be to have it as close to real time as possible.

**Comment by joeyespo** [comment]
Ok, I started with fractional intervals in cbbbfaa17673794e2821af040549c3d3fbe958e8, but then decided it might be simpler to use seconds instead. Implemented in #6.

**Comment by joeyespo** [comment]
Just published `v3.2.0` to the Chrome Web Store, which contains this fix. Thanks!

**Pull request merged**
