### PR TITLE
Fixed opening new tab while existing tab selected

### PR DESCRIPTION
**Pull request by shali3**
Hi Guys,
Love this extension, so first of all, thank you!
I got your update and you have a bug with selecting existing tabs.
I fixed it.

Please review and pull this fix.

### CODE REVIEW

**Comment by joeyespo** [comment]
👍

**Comment by joeyespo** [comment]
Thanks for the fix, @shali3! This did the trick. My mistake for not catching it sooner.

**Comment by joeyespo** [comment]
Just released v4.1.0 that includes this fix. Should propagate soon.

Thanks again, @shali3!

**Comment by shali3** [comment]
Happy to help :)

**Pull request merged**
